### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by mp1pro** [JessePeplinski/CodeAcademyProIntensive#1]
It is a better practice to have one project per repo instead of having several projects in one repo.

**Comment by Tereseus** [comment]
Yes you should revise your folder structure as it will be difficult for you to see what issues pertain to which project. and it is also more difficult to review your projects as we have to download quite a few projects.

**Comment by JessePeplinski** [comment]
Thanks for the feedback - normally I would split these into separate repos. To keep everything together, I decided to create one folder with multiple projects. I'd like to show this off to the public - so I did this to decrease the congestion. 🙂
