### ISSUE TITLE
Expresso Project - npm test

### ISSUE THREAD

**Issue by Tereseus** [JessePeplinski/CodeAcademyProIntensive#3]
I see another reviewer has already tested one of your projects. I am unsure if it was for the expresso project, that is why you need to make a different repo for each project. I ran your tests and all of the tests passed so good job there just be sure to move this and all the other projects to different repos. If you feel your github is getting congested with to many projects you can hide the projects from the public.

**Comment by JessePeplinski** [comment]
Thanks for the feedback - normally I would split these into separate repos. To keep everything together, I decided to create one folder with multiple projects. I'd like to show this off to the public - so I did this to decrease the congestion. 🙂
