### ISSUE TITLE
Expresso Summary

### ISSUE THREAD

**Issue by Tereseus** [JessePeplinski/CodeAcademyProIntensive#5]
Overall your project is exactly the way the solution wanted you to do the project as I found no errors whatsoever. Overall good job and if you have any questions feel free to ask.

**Comment by JessePeplinski** [comment]
Thanks for the feedback - much appreciated. Going forward, I'll be sure to split up the projects so it's easier for you and others to review.

**Comment by Tereseus** [comment]
Sounds good
